### ISSUE TITLE
verify development environment works in windows

### ISSUE THREAD

**Issue by kristus123** [kristus123/game-engine#8]
i am not able to test it on windows  unfortunately .
can anyone using windows try to follow the steps, if they don't work, can you make a suggestion/PR on what needs to be done.

thank you !!!!!!!!!1

**Comment by jalindarkachule123** [comment]
windows 11 is running on it , you can try it once.

**Comment by kristus123** [comment]
how did you make it run on windows 11 ?

**Comment by jalindarkachule123** [comment]
i am trying.Complete enverment setup for your project,If there is any problem i pig you

**Comment by jalindarkachule123** [comment]
hello sir , jinja2 issue not solve, plz help me

**Comment by jalindarkachule123** [comment]
hello sir , jinja2 issue not solve, plz help me

**Comment by jalindarkachule123** [comment]
Ok
